
---

## pod deployment

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: service-2
  name: service-2
spec:
  securityContext:
    runAsUser: 1000   #uid=100(curl_user) gid=101(curl_group) groups=101(curl_group)
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - image: dilshad007/service-1:0.0.2-SNAPSHOT
    name: service-2
    ports:
     - containerPort: 443
       name: https-2
    envFrom:
    - configMapRef:
        name: service-2-cm-1
    volumeMounts:
      - name: config-volume
        mountPath: /app/config/
        readOnly: false
      - mountPath: /truststore/
        name: tls-volume
      - name: cert-volume
        mountPath: /bindings/ca-certificates  
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  volumes:
  - name: cert-volume
    configMap:
      name: ca-configmap-2
  - name: config-volume
    configMap:
      name: service-2-cm-2
  - name: tls-volume
    csi:
      readOnly: true
      driver: csi.cert-manager.io
      volumeAttributes:
        csi.cert-manager.io/issuer-name: kms-issuer
        csi.cert-manager.io/issuer-kind: KMSIssuer
        csi.cert-manager.io/issuer-group: "cert-manager.skyscanner.net"
        csi.cert-manager.io/dns-names: '${POD_NAME},${POD_NAME}.${POD_NAMESPACE}.svc.cluster.local'
        csi.cert-manager.io/key-usages: server auth,client auth
        csi.cert-manager.io/duration: 8760h
        csi.cert-manager.io/renew-before: 72h
        csi.cert-manager.io/pkcs12-enable: 'true'
        csi.cert-manager.io/pkcs12-file: keystore.p12
        csi.cert-manager.io/pkcs12-password: changeit
        csi.cert-manager.io/fs-group: '1000'
  dnsPolicy: ClusterFirst
  restartPolicy: Always


---
## configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-2-cm-1
data:
  # property-like keys; each key maps to a simple value
  SERVER_PORT: "443"
  SPRING_CONFIG_IMPORT: "configtree:/app/config/"
  SERVICE2_URL: https://service-2:443/dummy
  JAVAX_LOG_LEVEL: TRACE
  JAVA_TOOL_OPTIONS: "-XX:ActiveProcessorCount=2 -Djavax.net.debug=ssl:handshake -Djavax.net.ssl.keyStore=/truststore/keystore.p12 -Djavax.net.ssl.keyStorePassword=changeit"
  BPL_JVM_THREAD_COUNT: "20" 
  SERVICE_BINDING_ROOT: "/bindings"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-2-cm-2
data:

    # mTLS
    server.ssl.client-auth: need

    # enable/disable https
    server.ssl.enabled: "true"

    # keystore format
    server.ssl.key-store-type: PKCS12

    # keystore location
    server.ssl.key-store: /truststore/keystore.p12

    # keystore password
    server.ssl.key-store-password: changeit

    # SSL protocol to use
    server.ssl.protocol: TLS

    # Enabled SSL protocols
    server.ssl.enabled-protocols: TLSv1.2

    server.ssl.trust-store: /layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts
    server.ssl.trust-store-password: changeit

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-configmap-2
data:
  type: ca-certificates

  udf-kms-issuer-ca.pem: |+
    -----BEGIN CERTIFICATE-----
    MIIDKjCCAhKgAwIBAgIVALpfFV/AWSQABWHMelgAT8+ef3EpMA0GCSqGSIb3DQEB
    CwUAMB0xGzAZBgNVBAMTEktNUyBJU1NVRVIgUk9PVCBDQTAeFw0xOTA4MzAwMDAw
    MDBaFw0yOTA4MjcwMDAwMDBaMB0xGzAZBgNVBAMTEktNUyBJU1NVRVIgUk9PVCBD
    QTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJgVHmAYJXCFBTzrkicQ
    bfkYDwrKOYc2XTLwFAOy64JQzixl46t11jQLZbY8miBGm2W6qog+KMRlrRGzNd3+
    oUy1V4hKcozPkQ5mNYYnATZiuMSyC/QosbI4ukNOW2wNNgfm46hallcca6SyRCTI
    7qpE9Sy/ACjK7CTTovVx6X+CIX4w95L//L3pw+2y8cxjSFf6+Sf64rFPvI6pDJ+z
    Cc2QnHjivoxjK5bOqDgiULd2CKZkHdilnDDmOSiZSD0XxJofJx4KLa+Tw0MQZoiC
    Me2m/bB2UANCVf7YbA5pb+bVWvWwW3Bn7LrM9fnTL4TfeRSMxAME6JvF2vmDeMYR
    RnMCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKEMB0GA1UdJQQWMBQGCCsGAQUFBwMC
    BggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSXMK0/E/9eTkm6
    zPLZjpy8Hkpe0TANBgkqhkiG9w0BAQsFAAOCAQEAAipiZUStRMhKFo83IRVp/pj5
    oP9DbC8XGHB7wgEr5QMRk87BgEKxX+bJhsJ0X8mYBeaOMKTcNaP35w9Lx++6SN2n
    Abfz/zRGznHUlGvAAPPEbuFna2hi1e8exz4ugc8QQkCGnuP6a5yVOgNqHOekxRhd
    YWRFUNQASFfrA97hl3tZ45srnIGRHbgllPGYuG2GMEQ8FaH+Ouqgk3l+zv0OKtUK
    fDgfZjq5acm6G3k9JbdX3NTA+lX5+3URezBgY6ZKxj01fZfQPSslYOh2DQXKl45S
    NzccFmvDPjmOjfCyV5nwzgdbCORbmaz+mN1TfQXg1wk306d5HUIOqmm16yz/XA==
    -----END CERTIFICATE-----
---
---
## service-2

apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  selector:
    run: service-2
  ports:
  - name: https-2
    protocol: TCP
    port: 443
    targetPort: https-2
